### ISSUE TITLE
Cannot Create Subscription Rule

### ISSUE THREAD

**Issue by WarrenKin** [paolosalvatori/ServiceBusExplorer#112] opened 2017-05-30 09:48 UTC
Hello Paolo,
I recently updated to the latest version after discussions with you last week about not being able to view the subscription messages, so now using 4.0.89.  However, I cannot seem to add/update a new/existing rule anymore.  The dialogue boxes appear for me to add/update the details but there are no action buttons e.g. add/update/cancel...etc  Am I doing something wrong?

![addsubscriptionrule](https://cloud.githubusercontent.com/assets/28863283/26577772/69cca0c6-4525-11e7-835f-24051c8c30fa.JPG)

**Comment by paolosalvatori** [comment] 2017-05-31 07:31
@SeanFeldman good observation. It looks like the issue is due to the resolution of your pc/laptop. I didn't make any change to the code of the rule control and I just tested the latest version on my pc and didn't see any issue with the rule control.

**Comment by WarrenKin** [comment] 2017-05-31 07:34
My display is the laptop recommended 1920x1080, what are you suggesting?

**Comment by paolosalvatori** [comment] 2017-05-31 07:57
Mmm... that's strange... it should work just fine, I'm using the same resolution. Did you change the size of text, apps and other items in the display settings? Are you using a value greater than 100%?

**Comment by WarrenKin** [comment] 2017-05-31 08:00
Yes, I’m on the laptop default 125%, I’ll change if you think this is the issue.

**Comment by paolosalvatori** [comment] 2017-05-31 08:03
@WarrenKin try to change the setting to 100% and let me know.

**Comment by WarrenKin** [comment] 2017-05-31 10:24
That’s done it, the action buttons have appeared, thank you.

**Comment by SeanFeldman** [comment] 2018-01-29 21:31
Looks like the issue was addressed, but tracking item never closed. Closing.
In case there's still an issue @WarrenKin, please reopen.

**Closed** 2018-01-29 21:31 UTC

**Comment by baltuonis** [comment] 2018-10-25 17:37
This was not fixed. Windows 7 DPI scaling 125% or 135% does not show action buttons.  But shows on 100%
![screenshot_2018-10-25_14 33 49](https://user-images.githubusercontent.com/188666/47519257-8afd0600-d863-11e8-9d9e-2c2b47fbafc9.png)
