### ISSUE TITLE
Trying to update existing saved connection

### ISSUE THREAD

**Issue by hgjura** [paolosalvatori/ServiceBusExplorer#274] opened 2018-10-31 03:23 UTC
Hi
I think this functionality exists now. But it seems the buttons are hidden behind a layer or something. See screen attached.

Also, how can I delete existing saved connections. I have quite a few now and would like to some clean up.

Thanks
Herald

![image](https://user-images.githubusercontent.com/9681487/47764260-bbe19e80-dc9a-11e8-85e9-bde978a4ca30.png)

**Comment by paolosalvatori** [comment] 2018-10-31 08:40
Hi @hgjura could you please tell us which version of Service Bus Explorer are you using on which Windows version? Thanks!

**Comment by hgjura** [comment] 2018-10-31 14:34
@paolosalvatori 
SBE 4.0.110
Windows 10 Version 1803 (OS Build 17134.345)

Thanks
Herald

**Comment by paolosalvatori** [comment] 2018-10-31 15:40
Can you please try to download and use the latest release? Thanks!

**Comment by hgjura** [comment] 2018-10-31 16:04
I really thought that 4.0.110 was the latest release, as per this page: https://github.com/paolosalvatori/ServiceBusExplorer/projects/1

**Comment by hgjura** [comment] 2018-10-31 19:51
I uninstalled SBE and reinstalled using chocolately. I have 4.0.110.
In the attached screenshot, any buttons to update or delete existing connections are not there.

Thanks
![image](https://user-images.githubusercontent.com/9681487/47814742-dd876800-dd24-11e8-9d8a-f12c58b814d9.png)

**Comment by hgjura** [comment] 2018-10-31 19:55
Also, while installing via chocolately, it does install SBE in the C:\ProgramData folder wheer SBE fails to save any connections because it does not have access to that folder. I had to move the ServiceBusExplorer folder out to another folder to make it work normally (which defeats the purpose of chocolately install).
Is this an issue only for me, or are there any instructions to get it done differently?  

Thanks
Herald

**Comment by ErikMogensen** [comment] 2018-10-31 21:05
Hi,
Regarding the missing buttons it is due to that the current release is from July and the buttons were added after that. So they should be there in the next release. You may download and build the develop branch if you'd like to get the buttons earlier.

About not having access to the Programdata folder it is unfortunately the way it works since that folder is by default protected. You may circumvent that by starting SBE as Administrator. The good news is that a solution for this will be part of the next SBE release since it will have the option to save settings and connection strings in a file in the Personal User file area. 

The code for this was recently merged into the develop branch, so again, if you download it you may build it and use this feature.

**Comment by hgjura** [comment] 2018-10-31 21:15
Thanks @ErikMogensen . I will get a good version from the dev version and work with it. I am glad both issue have been addressed.

**Comment by ErikMogensen** [comment] 2018-11-03 15:17
@hgjura, does it work it as expected for you now?

**Comment by hgjura** [comment] 2018-11-04 22:07
@ErikMogensen I did clone the repo locally and created in installable package. I can see the changes that you are talking about with the user config file and update/delete buttons for connection strings. 
However, when I try to register a connection with a connection string I get an: <17:05:42> InnerException: The remote server returned an error: (401) Unauthorized. claim is empty. TrackingId:d2955f0d-1546-4568-8a08-ca692148b0d3_G2, SystemTracker:dev-servicebus-integrations-acit.servicebus.windows.net:$Resources/Queues, Timestamp:11/4/2018 10:05:43 PM

The same connection string works fine in the older version, as I am copying and pasting it from the app.config file

**Comment by ErikMogensen** [comment] 2018-11-05 06:30
Good. 

Thank you for the feedback. However, you may request to extend the use of ACS to the 4th of February next year.

**Comment by paolosalvatori** [comment] 2018-11-06 11:20
Agreed, let's wait for the official announcement of ACS decommission, then we'll remove it from the connection options. Thanks for the feedback @hgjura

**Closed** 2019-03-04 18:21 UTC

**Comment by erizzo** [comment] 2019-07-01 12:56
I'm using version 4.1.112 on Windows Server 2012 R2, still have missing buttons.

![image](https://user-images.githubusercontent.com/333250/60438124-f14ddb80-9bdd-11e9-9923-3f0936fe2dff.png)

**Comment by paolosalvatori** [comment] 2019-07-17 09:18
Is this the latest release? If not, could you please download the latest version and retry? Do you observe the issue on other machines?

**Comment by erizzo** [comment] 2019-07-17 19:09
Version is 4.1.112 which is the latest Release I see here. I don't have any other Windows machine to try on.

**Comment by paolosalvatori** [comment] 2019-07-18 16:52
I can't reproduce the issue on my machine. Did you try to change screen resolution?

**Comment by ErikMogensen** [comment] 2019-07-18 19:32
@erizzo , unfortunately older versions of SBE always report their version as the latest released version since they get the version number using a REST call to Github. If your SBE states its version in the title of the main window it is an old version. The title should only say Service Bus Explorer, like the figure below:

![image](https://user-images.githubusercontent.com/9644248/61486217-35ddc300-a9a3-11e9-80fd-2269371999a2.png)

Do you have a version number in the title?

**Comment by erizzo** [comment] 2019-07-19 15:59
@ErikMogensen Thanks - that's a pretty nasty bug in the 4.0.x version I was actually using (showing the wrong version number in the title bar _AND_ the About dialog).
After getting the latest release I see the new connection management UI.

**Comment by paolosalvatori** [comment] 2019-07-29 13:49
@erizzo it was not a bug, it was intentional, but it's a long story :) We just decided to remove it as it was source of confusion :)
