### ISSUE TITLE
Exception: Could not contact host in connection string"

### ISSUE THREAD

**Issue by thiagosoeiro** [paolosalvatori/ServiceBusExplorer#459] opened 2020-07-05 22:15 UTC
I'm getting this error when trying to connect via Service Bus Explorer. My connection string is perfectly fine and works in my application. What may be wrong?

![CapturarSB](https://user-images.githubusercontent.com/9267122/86543368-2b8a4100-bef4-11ea-8bc4-338ab78856fc.PNG)

**Comment by SeanFeldman** [comment] 2020-07-06 17:25
I'd do the following to troubleshoot it
1. Validate that the connection works from a different environment (office, home, etc)
1. Check if you have a proxy in place that causes this. If so, you can [enable proxy](https://github.com/paolosalvatori/ServiceBusExplorer/pull/434) using the `develop` build compiled locally as it's not released yet.

**Comment by thiagosoeiro** [comment] 2020-07-07 23:17
> I'd do the following to troubleshoot it
> 
> 1. Validate that the connection works from a different environment (office, home, etc)
> 2. Check if you have a proxy in place that causes this. If so, you can [enable proxy](https://github.com/paolosalvatori/ServiceBusExplorer/pull/434) using the `develop` build compiled locally as it's not released yet.

1. Yes, it works fine. It even works inside my own environment connecting from c# code.
2. No proxy at all.

**Comment by ErikMogensen** [comment] 2020-07-08 09:51
That was strange. A couple of actions:

1. Please take a look at https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-troubleshooting-guide

Check ports:
80
443
9350 - 9354

2. Verify you are using the same ConnectivityMode in your C# program as in Service Bus Explorer.

3. Verify you are using the latest Service Bus Explorer version.

4. Double check your connection string.

5. If all of the above fail - create a case with Microsoft support unless there are any other ideas.

Please report back here for future reference and then we can hopefully close the issue.

**Comment by ErikMogensen** [comment] 2020-07-18 12:19
@thiagosoeiro , have you made any progress?

**Comment by ErikMogensen** [comment] 2020-08-20 06:20
Closing due to inactivity.

**Closed by ErikMogensen** 2020-08-20 06:20 UTC
Labels: question

**Comment by yolosh2020** [comment] 2025-02-07 11:24
Hi @ErikMogensen , I found this issue can be reproduced when I add PE for event hub. Even when I tried enable public along with PE in place, Service Bus explorer cannot connect with event hub successfully. Do you have any insight on this?

![Image](https://github.com/user-attachments/assets/fdad30f3-70d0-494e-a239-c085a36df3cb)

**Comment by ErikMogensen** [comment] 2025-02-07 17:20
@yolosh2020, does it work if you remove the private endpoint?

Second question: have you double checked that you have entered your outgoing IP address? One way of checking that is https://whatismyipaddress.com/. 

Third question: Are you using a proxy? Some proxies use different IP addresses for different destinations.

**Comment by yolosh2020** [comment] 2025-02-10 08:17
Hi @ErikMogensen ,
1. yes, it works when I remove the PE.

2. yes, I double checked the IP address. The IP address is set up correctly.

![Image](https://github.com/user-attachments/assets/9bd530fb-de4f-4510-8d96-76a53f403532)

3. There isn't any proxy in place.

![Image](https://github.com/user-attachments/assets/5a8b6496-b4a8-4189-9353-09e8cdaa03e4)
