### ISSUE TITLE
App locks up until all data is available, even though it already has enough to let user start browsing

### ISSUE THREAD

**Issue by ekevoo** [paolosalvatori/ServiceBusExplorer#51] opened 2016-08-03 14:48 UTC
A SB account of mine has about a hundred queues and a topic with almost a thousand subscriptions. On connection, it fetches details on each of those guys eagerly, which takes quite a while and most of it isn't immediately useful.

The app should allow the user to scroll through the list and select as soon as possible, fetching details in a deffered way, or, if possible, even lazy (no details until item is clicked).

**Comment by SeanFeldman** [comment] 2016-08-04 03:57
It's a good feature, but afraid not possible due to ASB SDK limitation.
The way to get all the entities is to invoke [`NamespaceManager`](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.namespacemanager.getqueues.aspx), which either fetches all the entities of a certain type, or a a filtered subset. Async overloads would help if the application support it, but it still would not be possible to fetch items in a lazy way.

**Comment by paolosalvatori** [comment] 2016-08-04 06:07
When you connect to a namespace, you decide which entities to retrieve and apply filters, for example to retrieve a subset of queues and topics (e.g. by name), so you don't need to retrieve all of them. So you can retrieve a subset of entities with their details, instead of retrieving all the entities in a given namespace.

**Comment by SeanFeldman** [comment] 2016-08-04 06:18
@paolosalvatori if I understood @ekevoo correctly, he was asking to fetch the names of all the entities w/o another details (number of messages, etc). The issue is that namespace manager will return a description for each entity (like [`QueueDescription`](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.queuedescription.aspx) for queues) and that would have all the data. Not possible to perform lazy loading due to API limitation.

**Comment by paolosalvatori** [comment] 2016-08-04 08:29
In this case, yes, I confirm what Sean just said.

**Comment by ekevoo** [comment] 2016-08-05 19:46
That was just a method suggestion. I understand if it's not viable.

Let's say I want to quickly work with queues. Yet, there's a topic with 2000 subscriptions that takes roughly 3 minutes to load. I have to wait 3 minutes to even *see* the queues.

I'm editing the title to make the real problem clearer. Regardless of API limitations, there's data that is available at the client within miliseconds, that can be used and thus surrender control back to the user immediately, updating the listings as more data becomes available.

**Comment by ekevoo** [comment] 2016-08-05 19:48
The general principle here is "don't wait until desserts are served before you start eating lunch".

**Comment by SeanFeldman** [comment] 2016-08-05 20:04
@ekevoo good that you edited the title and clarified exactly what you were looking for. Clarity helps.
I presume the application was not created with scenario you've described in mind. 
Your suggestion is good. Want to send a PR?

**Comment by paolosalvatori** [comment] 2017-03-09 10:21
@ekevoo maybe you didn't read what I said at the beginning of this thread. In the connect form you can decide which entities you want to load and apply filters. This way you can load only the entities you have to work with. I close this request as in my opinion, the tool already does what you are asking for.

**Closed by paolosalvatori** 2017-03-09 10:21 UTC
