### ISSUE TITLE
Active Message Count Negative v4.0.94

### ISSUE THREAD

**Issue by KSib** [paolosalvatori/ServiceBusExplorer#124] opened 2017-06-21 13:30 UTC
Is this by design or should it be possible for a subscription to have a negative active message count? If I navigate to the portal, I don't see any negative numbers. That seems odd. What would a negative number be telling me?

Here's what I have

- Topic: topic1
    -   Subscription: 123456 (-2, 3)
    -   Subscription: 567890 (5, 3)
    -   Subscription: catchall (13, 0)

Is this just Message Count - DeadLetter Message Count? Wouldn't users just want to see the message count (message count, dead letter message count)?

Thanks.

**Comment by paolosalvatori** [comment] 2017-06-21 15:25
Yes, the two numbers you can see are respectively the number of active messages and the number of messages in the deadletter queue. I've never seen negative numbers for these two properties. Can you please use the Azure Portal to compare the number of active messages and deadletter messages in your subscriptions?

**Comment by KSib** [comment] 2017-06-21 15:36
Here's what I have

**Service Bus Explorer**
![image](https://user-images.githubusercontent.com/1589238/27392791-35ea0f56-566d-11e7-8b5a-30be53773dea.png)

**Portal**
![image](https://user-images.githubusercontent.com/1589238/27392828-4dea96de-566d-11e7-841d-614dec118d91.png)

**Comment by paolosalvatori** [comment] 2017-06-21 16:00
The topic never reports the number of messages. So this is correct. Can you please send me the latest picture for the 123456 subscription? Thanks

**Comment by KSib** [comment] 2017-06-21 16:07
It looks like it's now at (1,3,0)

![image](https://user-images.githubusercontent.com/1589238/27394339-6df781fe-5671-11e7-9ef7-25e3a4f5a16a.png)

I also disabled "Enable Dead Lettering On Filter Evaluation Error" and enabled "Enable Dead Lettering On Message Exception" so I don't know if that's related? Or maybe something got cached funny? I'm not sure.

**Comment by SeanFeldman** [comment] 2017-06-21 16:10
@KSib I've noticed in the title of this issue that you've used version "v4.0.68". Are you still using that version? The latest can be found [here](https://github.com/paolosalvatori/ServiceBusExplorer/releases).

**Comment by KSib** [comment] 2017-06-21 16:11
I'm on 4.0.94 now when I posted the most recent screenshot. It doesn't seem to be happening anymore though after disabling "Enable Dead Lettering On Filter Evaluation Error" so maybe it's fine now?

**Comment by SeanFeldman** [comment] 2017-06-21 16:20
I'm not convinced "Enable Dead Lettering On Filter Evaluation Error" is the issue. Active message count is a counter reported by ASB. It shouldn't be reported as a negative value. If you enable that option again and see negatives, I'd say raise an issue. Active messages (at least the way I understand) are the messages that are reported _after_ dead-lettering and everything else.

**Comment by KSib** [comment] 2017-06-21 16:31
I guess I need to raise an issue with MSFT. I reproduced it.

Create a subscription and have "Enable Dead Lettering On Filter Evalulation Error" enabled.
Have a filter like test='123'
Send a message to the parent topic via REST with a header key/value pair: test, 123. Note how the 123 in the header isn't in quotes, so it will be treated like an int.

The message will go into the DLQ with the following message:

DeadLetterReason	String	FilterException
DeadLetterErrorDescription	String	Operator '==' cannot be applied to operands of type 'int' and 'string'

![image](https://user-images.githubusercontent.com/1589238/27395333-0d75948e-5675-11e7-827f-ab081eecef55.png)

**Comment by KSib** [comment] 2017-06-21 18:39
I posted here: https://social.msdn.microsoft.com/Forums/en-US/da789d32-b08d-4d1b-8bb6-bdf280aae135/c-net-subscription-active-message-count-negative?forum=servbus

I'll report back if I hear anything. I don't have a subscription to have direct MSFT support so the forums or twitter will have to do for now.

**Comment by paolosalvatori** [comment] 2017-06-22 14:10
Who knows... Well, I'll close this issue for now :)

**Closed by paolosalvatori** 2017-06-22 14:10 UTC

**Comment by SeanFeldman** [comment] 2017-06-22 14:40
👍 @KSib 
Please let us know when you get to the bottom of this. In case it is an issue with SBE, we'll re-open the issue and handle it as per guidance provided by MSFT support.

**Comment by stofte** [comment] 2017-06-23 09:06
Just came by because I was surprised by seeing negative counts in the Active Message thingy. I don't believe I've seen this before.

**Comment by SeanFeldman** [comment] 2017-06-23 13:16
Can you reliably reproduce it?

**Comment by KSib** [comment] 2017-06-23 14:46
I did above? What do you mean @SeanFeldman

**Comment by stofte** [comment] 2017-06-23 15:10
@KSib I guess he was asking me :)

@SeanFeldman: I havent tried to create a minimal testcase (I probably wont have time either). I just wanted +1 the issue, since I just started noticing it yesterday.

**Comment by SeanFeldman** [comment] 2017-06-23 15:50
Sorry for confusion @KSib. My reply was targeting @stofte 's comment.

@stofte if you do find a repro you could share, please do. Numbers are no calculated by SBE, so I wonder if that's a broker issue. Or ASB client for that matter.

**Comment by binzywu** [comment] 2017-07-05 19:04
To confirm it is a service side issue. The fix will be deployed in the next release cycle. The issue impacts only in this scenario (deadletter on filtering error) and only for the in memory stats. Messages and the true statistic/data is not impacted. Which means this doesn't impact any runtime operations and if the entity is reloaded, the number will be corrected.

**Comment by SeanFeldman** [comment] 2017-07-05 19:20
Thank you for the confirmation @binzywu 
I wish there was a bug tracked somewhere on GH (😉) we could link to.

**Comment by paolosalvatori** [comment] 2017-07-06 08:19
Thanks @binzywu for the confirmation! :)

**Comment by danielok1993** [comment] 2017-07-11 08:37
@binzywu We have also managed to replicate the issue for both Queues and Topics by trying to Defer the dead letter message which has Delivery Count bigger than Max Delivery Count. Will the upcoming fix cover this scenario as well?

**Comment by binzywu** [comment] 2017-10-12 06:13
I completely forgot this issue. Just to circle back to confirm the fix was rolled out couple month back.

**Comment by paolosalvatori** [comment] 2017-10-12 16:04
Thanks @binzywu for the follow up
