### ISSUE TITLE
Error when sending message

### ISSUE THREAD

**Issue by NatashaRad** [paolosalvatori/ServiceBusExplorer#311] opened 2019-03-07 19:40 UTC
Hi,
I have successfully downloaded, built ServiceBusExplorer solution (ServiceBusExplorer 4.1.111) and got connected. But when I try sending a message, I am getting error: Exception: Could not load type 'Microsoft.ServiceBus.Messaging.MessagingEntityClient' from assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Please help me to solve the problem.
Thank you.

**Comment by ErikMogensen** [comment] 2019-03-07 20:44
Hi,

A couple of questions:

1. Is Microsoft.ServiceBus.dll in the same directory as ServiceBusExplorer.exe?
2. If you download the package from https://github.com/paolosalvatori/ServiceBusExplorer/releases and then run it. Does that work?
3. Is Microsoft.ServiceBus.dll in your GAC?

**Comment by NatashaRad** [comment] 2019-03-07 21:34
Natalya Radutskaya
Application Developer, Sr
King County Information Technology
BSS Property Systems
(206) 263-7857
natalya.radutskaya@kingcounty.gov<mailto:natalya.radutskaya@kingcounty.gov>

**Comment by SeanFeldman** [comment] 2019-03-07 22:50
One more check @NatashaRad, are you running the app from a network drive?
If yes, copy it to a local drive and re-run.

**Comment by NatashaRad** [comment] 2019-03-07 23:00
I am running it from my machine.
First time I downloaded the solution, built it and run from the bin folder.
Then I tried to install it from Microsoft store, same version, launch it and still get the same error.

Natalya Radutskaya
Application Developer, Sr
King County Information Technology
BSS Property Systems
(206) 263-7857
natalya.radutskaya@kingcounty.gov<mailto:natalya.radutskaya@kingcounty.gov>

**Comment by SeanFeldman** [comment] 2019-03-07 23:11
> Then I tried to install it from Microsoft store, same version, launch it and still get the same error.

Microsoft Store? It's not on Microsoft store AFAIK....

Also, @NatashaRad, do you mind not to reply from your email with the entire email thread in the body? It create an [enormous noise](https://github.com/paolosalvatori/ServiceBusExplorer/issues/311#issuecomment-470735647) when looking at the issue on GitHub... hope you don't mind 🙂 When replying using email, just send your comment, delete everything else. Thanks.

**Comment by NatashaRad** [comment] 2019-03-07 23:15
Sorry…
It is in Microsoft Store, they mention
Copyright
https://github.com/paolosalvatori/ServiceBusExplorer
Developed by
https://github.com/paolosalvatori/ServiceBusExplorer

Natalya Radutskaya
Application Developer, Sr
King County Information Technology
BSS Property Systems
(206) 263-7857
natalya.radutskaya@kingcounty.gov<mailto:natalya.radutskaya@kingcounty.gov>

**Comment by SeanFeldman** [comment] 2019-03-07 23:49
@NatashaRad this application is only available via
- GitHub 
  - As code
  - As compiled and packaged into zip (here: https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest)
- Chocolatey package - https://chocolatey.org/packages/ServiceBusExplorer/

Please use one of these to download the tool. Thank you.

**Comment by NatashaRad** [comment] 2019-03-07 23:52
This exactly what I used first time and it didn’t work! While all my coworkers were able to get it successfully.

Natalya Radutskaya
Application Developer, Sr
King County Information Technology
BSS Property Systems
(206) 263-7857
natalya.radutskaya@kingcounty.gov<mailto:natalya.radutskaya@kingcounty.gov>


@NatashaRad<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNatashaRad&data=02%7C01%7CNatalya.Radutskaya%40kingcounty.gov%7Cb37a8803e2b443c2c80d08d6a357954b%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C636875993892532015&sdata=jFlX%2F%2BaAA2VeTEovhdNzA7%2BuP9tN9afEaeFnO3Qs3wQ%3D&reserved=0> this application is only available via

  *   GitHub
     *   As code
     *   As compiled and packaged into zip (here: https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpaolosalvatori%2FServiceBusExplorer%2Freleases%2Flatest&data=02%7C01%7CNatalya.Radutskaya%40kingcounty.gov%7Cb37a8803e2b443c2c80d08d6a357954b%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C636875993892542028&sdata=Po3DShIQCaQP7yzr46TO%2BNVRWQRm1lUvrw4B%2Byp9lFg%3D&reserved=0>)
  *   Chocolatey package - https://chocolatey.org/packages/ServiceBusExplorer/<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchocolatey.org%2Fpackages%2FServiceBusExplorer%2F&data=02%7C01%7CNatalya.Radutskaya%40kingcounty.gov%7Cb37a8803e2b443c2c80d08d6a357954b%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C636875993892542028&sdata=lUmp3WNsWPLJK3zFX3R3%2BlkOPtkhmwWDfI1foyxhYHE%3D&reserved=0>

Please use one of these to download the tool. Thank you.

**Comment by NatashaRad** [comment] 2019-03-07 23:54
I have tried version from Microsoft only an hour ago. 2 days I was fighting with what I got from sites below.

Natalya Radutskaya
Application Developer, Sr
King County Information Technology
BSS Property Systems
(206) 263-7857
natalya.radutskaya@kingcounty.gov<mailto:natalya.radutskaya@kingcounty.gov>


@NatashaRad<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNatashaRad&data=02%7C01%7CNatalya.Radutskaya%40kingcounty.gov%7Cb37a8803e2b443c2c80d08d6a357954b%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C636875993892532015&sdata=jFlX%2F%2BaAA2VeTEovhdNzA7%2BuP9tN9afEaeFnO3Qs3wQ%3D&reserved=0> this application is only available via

  *   GitHub
     *   As code
     *   As compiled and packaged into zip (here: https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpaolosalvatori%2FServiceBusExplorer%2Freleases%2Flatest&data=02%7C01%7CNatalya.Radutskaya%40kingcounty.gov%7Cb37a8803e2b443c2c80d08d6a357954b%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C636875993892542028&sdata=Po3DShIQCaQP7yzr46TO%2BNVRWQRm1lUvrw4B%2Byp9lFg%3D&reserved=0>)
  *   Chocolatey package - https://chocolatey.org/packages/ServiceBusExplorer/<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchocolatey.org%2Fpackages%2FServiceBusExplorer%2F&data=02%7C01%7CNatalya.Radutskaya%40kingcounty.gov%7Cb37a8803e2b443c2c80d08d6a357954b%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C636875993892542028&sdata=lUmp3WNsWPLJK3zFX3R3%2BlkOPtkhmwWDfI1foyxhYHE%3D&reserved=0>

Please use one of these to download the tool. Thank you.

**Comment by SeanFeldman** [comment] 2019-03-07 23:57
@NatashaRad if all of your co-workers were able to use it and you can't, that would isolate the issue to your machine. Try to download and use it on another machine, to verify it's the machine that has a problem. Which is likely the issue. Once you've identified it's the machine, have a look at your user vs others. Is there any difference? Is your account restricted? Is file getting corrupted somehow? Etc.

Reply from email is evil... see for yourself https://github.com/paolosalvatori/ServiceBusExplorer/issues/311#issuecomment-470748918

**Comment by SeanFeldman** [comment] 2019-03-07 23:58
> I have tried version from Microsoft only an hour ago. 2 days I was fighting with what I got from sites below.

I am not aware of this application being distributed via Microsoft store. Could you please provide a link or a screenshot of where you're getting if from? Thank you.

**Comment by NatashaRad** [comment] 2019-03-08 00:01
https://www.microsoft.com/en-us/p/service-bus-explorer/9n454whqdsw1?activetab=pivot:overviewtab

[cid:image003.jpg@01D4D4FF.0D6B1EA0]

[cid:image004.jpg@01D4D4FF.0D6B1EA0]

Natalya Radutskaya
Application Developer, Sr
King County Information Technology
BSS Property Systems
(206) 263-7857
natalya.radutskaya@kingcounty.gov<mailto:natalya.radutskaya@kingcounty.gov>

**Comment by SeanFeldman** [comment] 2019-03-08 00:18
@NatashaRad please use GitHub UI. Your screenshots are not coming through when sent using an email client.

**Comment by dbreit7** [comment] 2019-03-30 00:29
Hi all,

I get the same error starting with version 4.1.111. (4.1.112 and 4.1.113 also)
<16:59:29> Exception: Could not load type 'Microsoft.ServiceBus.Messaging.MessagingEntityClient' from assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

This assembly is in the GAC:   Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL

The error goes away and I can send messages If I revert to 4.0.110 using the choco install command: 
> choco install servicebusexplorer --version 4.0.110 --force

Thank you,
dbreit

**Comment by dbreit7** [comment] 2019-03-30 05:20
Following up on my message from five hours ago, I just tried sending a message using 4.1.111 on a different computer and it works fine.  If I can help by providing any additional diagnostic info from my other computer, please let me know.

**Comment by ErikMogensen** [comment] 2019-03-30 17:27
If you are able to build it, please get the latest version from the develop branch and verify that it still has that problem. Then update WindowsAzure.ServiceBus to the latest version (5.1). 

If this still does not work, I was going to suggest to you to downgrade WindowsAzure.ServiceBus to 4.1.11, but I just tried the downgrade and I got two dependency conflicts. If downgrade anyway and you are able to resolve the conflicts please let us know the result.

**Comment by SeanFeldman** [comment] 2019-04-01 03:57
@dbreit7 check that you're not loading from a network drive. When extracting files, unblock them. See if `WindowsAzure.ServiceBus` is found on the disk and what version it is.

**Comment by NatashaRad** [comment] 2019-04-01 14:59
Hi,
I got a new laptop and still have to use the older version.

Natalya Radutskaya
Application Developer, Sr
King County Information Technology
BSS Property Systems
(206) 263-7857
natalya.radutskaya@kingcounty.gov<mailto:natalya.radutskaya@kingcounty.gov>

**Comment by dbreit7** [comment] 2019-04-01 20:00
@ErikMogensen Success! I built from develop branch and verified it still had the error.  Then I upgraded WindowsAzure.ServiceBus to 5.1 and had the same error.  When I downgraded to 4.1.111, I had to fully qualify some namespaces in four files (ServiceBus.TokenProvider became Microsoft.ServiceBus.TokenProvider, ServiceBus.NamespaceManager became Microsoft.ServiceBus.NamespaceManager, etc.) but it has eliminated the error I was getting when using the "Send Messages" action.  

@SeanFeldman I can confirm that when I downloaded a zip of the repo, I did unblock files with 
>gci -Recurse . | Unblock-File
In my .nuget\packages\windowsazure.servicebus 2.3.1, 3.4.5, 4.0.0, 4.1.11, 4.1.2 , 4.1.6, 4.1.7, 4.1.8, 5.0.0, and 5.1.0.  I'm running everything from a local drive.

**Comment by paolosalvatori** [comment] 2019-06-11 08:41
Thanks for the follow up @dbreit7 and sorry for the delayed answer, I will proceed and close the issue.

**Closed by paolosalvatori** 2019-06-11 08:41 UTC
Labels: question

**Comment by mattisking** [comment] 2021-09-10 18:06
So, this is still happening for me in 2021 with the package from chocolately, version 5.0.4 on Windows 10. Is there something that needs to happen here still? It doesn't seem truly fixed. I'll try to build it myself with suggestions from above, but it might be worth seeing what's wrong in the build going out.

**Comment by AlexanderGurinov** [comment] 2021-09-12 12:07
Same error when trying to repair and resubmit from DLQ.
<15:04:13> Exception: Could not load type 'Microsoft.ServiceBus.Messaging.MessagingEntityClient' from assembly 'Microsoft.ServiceBus, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
The dll in the same folder as exe:
![image](https://user-images.githubusercontent.com/2279213/132986910-bc10d030-6f38-4d87-b5ff-48e440ad8575.png)
I'm using version 5.0.4 downloaded from a zip file from releases for this repo.

**Comment by bh3605** [comment] 2022-02-07 14:05
Downloaded version 5.0.4 zip and it didn't work out of the box. Had to install Microsoft.ServiceBus.dll in to the GAC.

**Comment by ErikMogensen** [comment] 2022-02-07 16:23
@bh3605, do you know if there were already a registered Microsoft.ServiceBus.dll in the GAC? That seems to be the reason for this issue. For more info see the comment https://github.com/paolosalvatori/ServiceBusExplorer/issues/561#issuecomment-860068010. 

Also, if you or anyone else, run into this issue in the future it would be very helpful if you setup fuslogvw according to https://github.com/paolosalvatori/ServiceBusExplorer/issues/525#issuecomment-801330494 and reproduced the issue. Then put the log here.

**Comment by bh3605** [comment] 2022-02-07 20:19
Maybe there was? I don't remember. I only remember this stop working for me months ago and I needed this to work yesterday.

3.0.0 of Microsoft.Servicebus was installed in the GAC. Uninstalling and trying again works now. Thanks
