### ISSUE TITLE
Copy messages among Queues and Topics via Service Bus Explorer UI

### ISSUE THREAD

**Issue by PingPongSet** [paolosalvatori/ServiceBusExplorer#350] opened 2019-05-24 17:00 UTC
Is it possible to copy messages including body and headers in a queue to another queue or Topic?

**Comment by SeanFeldman** [comment] 2019-05-24 18:26
If it's a single message on a queue or all messages, then you can use Auto-Forwarding which can be configured using SBE UI. After that, you can disable Auto-forwarding. In case you're referring to a single message peeked from a queue, I don't believe that feature exists. Would be a nice contribution though 😉

**Comment by SeanFeldman** [comment] 2019-05-24 18:30
Sorry, I should have thought about it. You _can_ do it, by right-clicking the peeked message and selecting "Repair and Resubmit..." option. Note that this is NOT going to move the original message to the desired destination, but a copy. You will have the source message remaining in the original queue.

In case that works for you, please close the issue.
Otherwise, I would suggest to replace it with a different one that is about "**Moving** a message from one entity to another".

**Comment by PingPongSet** [comment] 2019-05-24 20:49
"Repair and Resubmit..." option works for when one message is selected. 

However, when more than one message are selected and selecting "Repair and Resubmit...", the window is squeezed like below:

[https://i.imgur.com/YBXvgw2.png](https://i.imgur.com/YBXvgw2.png)

**Comment by ErikMogensen** [comment] 2019-05-25 08:01
@PingPongSet , that is by design. The reason for this is that don't have the option to edit multiple messages.

**Closed** 2019-05-25 16:39 UTC
Labels: question
