### ISSUE TITLE
Purge Messages feature is broken

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [paolosalvatori/ServiceBusExplorer#509] opened 2021-01-14 17:34 UTC
Currently in v5.0.1 trying to purge a topic subscription results in the following error message printed to the log.

`<11:26:33> Exception: Invalid URI: The hostname could not be parsed.`

Purging the DLQ seems to work however.

**Comment by ErikMogensen** [comment] 2021-01-14 20:05
It works for me. It may be a temporary problem due to a network issue or high load on the Service Bus service. If the issue persists, try to purge a subscription on another topic. Also increase the Receive timeout and Server timeout settings. 

Do you know if you are connecting to Service bus through a proxy?

**Comment by ErikPilsits-RJW** [comment] 2021-01-14 21:10
I've tried a couple different topics and subscriptions, same issue. Here's all my config, redacted, maybe it's relevant for your testing.
![image](https://user-images.githubusercontent.com/68246095/104649534-7ee70400-567a-11eb-9d98-a0e0d0edfd95.png)
![image](https://user-images.githubusercontent.com/68246095/104649578-8ad2c600-567a-11eb-8690-8d4a4592a075.png)
![image](https://user-images.githubusercontent.com/68246095/104649598-93c39780-567a-11eb-83a8-c97cf4dcdd47.png)

**Comment by ErikPilsits-RJW** [comment] 2021-01-14 22:24
Also, receiving messages a creating a listener both work. In fact, Purge has always been a bit weird with session enabled topics, so I've been using the listener with a bunch of parallel sessions to "purge" a subscription.

Btw I think the metrics with the listener are wrong with sessions. I think it's counting sessions received and not messages received. I cleared 12 messages with it, and it reported 4. I think there were probably 4 sessions in there.

**Comment by ErikPilsits-RJW** [comment] 2021-01-14 22:37
Oh and no, not using a proxy.

**Comment by paolosalvatori** [comment] 2021-01-15 08:42
@ErikPilsits-RJW Can you please try to install the same version of SBE and repeat the same operation against the same topic\subscription?
Are you using a connection string at the namespace level with the manage claim? We need to be able to reproduce the issue, if any, to fix it.

**Comment by ErikPilsits-RJW** [comment] 2021-01-15 14:29
Can you clarify what you mean by "install the same version"? I downloaded the zipped version 5.0.1 from github, and that's what I tested with. I'm using the root key for testing at the moment, so it has full permissions.

**Comment by ErikPilsits-RJW** [comment] 2021-01-15 14:32
Anyway, the problem has to do with subscriptions that have sessions enabled. I created a new subscription under an existing topic, but did not enable sessions, and the purge function works. So, create a session enabled sub and see if you can repro.

**Comment by ErikMogensen** [comment] 2021-01-15 17:20
@ErikPilsits-RJW , I was able to reproduce it on a session subscription queue. I have changed the implemention in the develop branch to use the latest Service Bus SDK and the purging worked for me. I think there is some bug in the previous version of the SDK. 

Are you able to build from the develop branch? In that case, try it and please report back here.

**Comment by paolosalvatori** [comment] 2021-01-15 19:12
Perfect, thanks for the feedback. Let us know if we can close the issue.

**Comment by ErikPilsits-RJW** [comment] 2021-01-15 20:02
Yes we can close this, thank you

**Comment by ErikMogensen** [comment] 2021-01-16 10:06
@ErikPilsits-RJW, does it show the correct count when using the build from the develop branch?

**Comment by ErikPilsits-RJW** [comment] 2021-01-18 14:35
It doesn't seem to, no.

![image](https://user-images.githubusercontent.com/68246095/104928336-20ff3880-5968-11eb-8131-750dcb78f60e.png)
![image](https://user-images.githubusercontent.com/68246095/104928358-29f00a00-5968-11eb-8832-f6ed2e07724c.png)

**Comment by ErikMogensen** [comment] 2021-01-18 20:51
Ok. so the UI is wrong. What about the report in the log, like the sample below:

> `<11:35:24> [54] messages have been purged from the [xx/Subscriptions/xx] subscription in [41] seconds.`

**Comment by ErikPilsits-RJW** [comment] 2021-01-18 21:08
I believe the Purge gets the correct count. Just the listener feature that is incorrect.

**Comment by ErikMogensen** [comment] 2021-01-19 06:49
Created #512 for that. I'll create another issue for the purging of session subriptions.

**Closed by ErikMogensen** 2021-01-19 06:49 UTC
