### ISSUE TITLE
Pressing "Delete" on Queue / Topic should warn with a pop up box

### ISSUE THREAD

**Issue by AizazAlam2000** [paolosalvatori/ServiceBusExplorer#484] opened 2020-12-18 23:53 UTC
When a Queue or Topic is selected and the **Delete** button is pressed the item is deleted immediately. 
This can be pressed by mistake and cause issues in a production environment. 

It would be great to have a pop up box come up which will give us a warning and prompt us if we are sure we want to do this. 

Loving the product overall !!

**Comment by SeanFeldman** [comment] 2020-12-19 00:06
When <kbd>Delete</kbd> is pressed, there's a warning dialog box.

![image](https://user-images.githubusercontent.com/1309622/102674317-da44d580-4152-11eb-8bb6-21458600fd6a.png)

Also, there was already a [PR](https://github.com/paolosalvatori/ServiceBusExplorer/pull/437) addressing this exact concern.
It will be soon released as v5. If you need it immediately, you could compile the project locally and use it.

Closing as a duplicate of https://github.com/paolosalvatori/ServiceBusExplorer/pull/437.

**Closed by SeanFeldman** 2020-12-19 00:06 UTC
