### ISSUE TITLE
Deleting single message from a queue

### ISSUE THREAD

**Issue by chuckdawit** [paolosalvatori/ServiceBusExplorer#228] opened 2018-06-15 05:31 UTC
I would like the ability to delete a single message from a queue! thanks.

**Comment by SeanFeldman** [comment] 2018-06-15 05:33
@chuckdawit please elaborate on your use case. Are you referring to deletion by sequence number?

**Comment by chuckdawit** [comment] 2018-06-15 06:04
Hi Sean.

Yes, by sequence number. Right now it seems like the only way I can delete
a single message is by code/script or by deleting the entire queue.
If there is a way to delete a single message by sequence number in service
bus explorer please let me know.
I can see the data associated with each message, I just would like the
ability to delete a message in a queue without removing the whole queue.

Thanks for any advice!

Chuck

**Comment by SeanFeldman** [comment] 2018-06-15 06:15
As of today you can purge or receive and delte number of messages, but you can delete a message by sequence number. This would be a feature to add.

**Comment by chuckdawit** [comment] 2018-06-15 06:33
If I understand you correctly, I can purge a queue and that will delete all
messages in the queue, but not the queue itself?
But I can't delete a single message by sequence number.
Is that correct?
Chuck

**Comment by ErikMogensen** [comment] 2018-06-15 08:50
This seems to be a duplicate of #135.

**Comment by ErikMogensen** [comment] 2018-06-15 11:53
@chuckdawit , on deadletter subqueues it is possible to delete a specific message as long it is not too far down (depending upon settings, location, message size and other things). Is that what you are looking for?

**Comment by chuckdawit** [comment] 2018-06-15 18:59
possibly but I'll have to look to see what deadletter means. I'm a little
new to messing queues in Azure.
My message is pretty simple, no info, just the sequence number.
Chuck

**Comment by ErikMogensen** [comment] 2020-08-20 06:25
Closing due to inactivity

**Comment by ErikMogensen** [comment] 2024-07-31 06:23
See the discussion at #771

**Closed by ErikMogensen** 2024-07-31 06:23 UTC
Labels: Feature
