### ISSUE TITLE
Application freezes after I open messages for a subscription (probably proxy-related)

### ISSUE THREAD

**Issue by javafrog** [paolosalvatori/ServiceBusExplorer#204] opened 2018-04-04 15:42 UTC
I can start the application and connect to a certain service bus instance and see all the topics and subscriptions. However, when I want to send a new message or open the messages for a certain topic subscription, the application freezes and does never recover (mouse cursor shows loading icon). This only seems to happen in my corporate network, when I use an open hotspot, the problem does not occur.

I assume there is a problem with making a connection, but an error message would be more helpful.

**Comment by SeanFeldman** [comment] 2018-04-04 15:55
@javafrog what version of the tool are you using? https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/4.0.109 just came out and supposed to address this issue. 

Please confirm.

**Comment by javafrog** [comment] 2018-04-05 06:28
The whole situation is somewhat unclear, but let me give you some more details:
- We have several colleagues experiencing the same problems
- In public WiFi, there seem to be no issues
- In LAN mode (we have a proxy), the reported problems occur all the time
- One colleague reported the freezes are gone with version 4.0.109 when connecting via our company WiFi. That WiFi is also restricted, but not as much as the LAN.

**Comment by ErikMogensen** [comment] 2018-04-05 07:34
@SeanFeldman, I am not behind a proxy currently so I am unable to verify v4.0.109. 

@javafrog, have you configured the proxy connection in the config file?

**Comment by ErikMogensen** [comment] 2018-04-05 07:41
How to configure the proxy connection in the config file is described at https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration. 

If Connectivity Mode (in the Options dialog windows) = AutoDetect does not work try with Http or Https.

**Comment by raymaung** [comment] 2018-04-06 00:10
I had similar issue as @javafrog. Using a corporate network, it didn't have any issue fetching the service meta data, however, when I tries to fetch the messages  **first** time, it freezes.

After 5-10 min, I kill it, try again for a few times, same issue. In one case, I let it run for a little longer, then it fetches the messages. And subsequent fetches are fast. First time freezing is true every time after restarting ServiceBusExplorer.

It appears there is something going on during the first fetch; I wish I could provide logs but can't find it.

**Comment by paolosalvatori** [comment] 2018-04-06 05:25
Hi @raymaung when did you start to experience this problem? I mean, did you observe the same issue with previous versions of the tool or only with a recent version? Thanks!

**Comment by javafrog** [comment] 2018-04-06 12:04
Thanks for your comments! I did configure the proxy in the config file, with the same results, before I created this issue.

Today, however, it worked just as @raymaung described: The first connection took a while, appearing like a freeze. Then after like 30 seconds, the messages appeared. Subsequent accesses were quick. I did try it from our (most restrictive) LAN.

I also don't know if there are any logs written somewhere that I could provide you.

**Comment by raymaung** [comment] 2018-04-09 01:01
@paolosalvatori I should clarify `4.0.108` - just frozen. `4.0.109` **eventually** fetches the first message after many minutes.

**Comment by raymaung** [comment] 2018-04-10 02:17
@paolosalvatori I tested different versions against the same corporate network and here are the results

- `4.0.105`
  - won't even load the meta data
- `4.0.106` to `4.0.108`
  - load the meta data
  - freeze on **first time** fetching messages
- `4.0.109`
  - take awhile to complete the **first messages fetch**
  - fast on subsequent messages fetch

**Comment by ErikMogensen** [comment] 2018-04-10 08:52
When using SBE to connect to SB through a proxy the following four requirements must be met:

- The SBE config file must be properly configured for the proxy used. This is described at https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration. SBE needs to be restarted after a config file change.

- Connectivity Mode must be AutoDetect, Http or Https. This is set when connecting to a namespace. Test all three modes.

- SBE must be using a version of the SB Client that does not have the Http/Https bug. So either use a really old version of SBE or the latest, 4.0.109.

- The proxy must allow traffic to SB and properly handle it. 

As I understand it @raymaung this has never worked for you. I therefore believe that the issue is inside the proxy. When loading meta data the SB Client uses normal REST calls but when sending or receiving messages in Connectivity Mode in Http or Https (or AutoDetect has choosen one of the latter modes) the SB Client tunnels the traffic in HTTP or HTTPS to be able to get through the proxy and this could be tricky. I know that in one case a change had to be made on the proxy to allow this tunneled traffic. I recommend opening a case with Microsoft to solve this. If you are lucky they have information about how to configure your proxy. If not then they will probably need network traces to find out what is wrong.

**Comment by ErikMogensen** [comment] 2018-10-24 15:46
Closing this as there has not been any comments in the last six months.

**Closed by ErikMogensen** 2018-10-24 15:46 UTC
