### ISSUE TITLE
Enable authentication using managed identity token provider

### ISSUE THREAD

**Issue by naebliss** [paolosalvatori/ServiceBusExplorer#408] opened 2020-01-08 14:57 UTC
Can we make it possible to use managed identities for authenticating to a service bus namespace from ServiceBusExplorer?

We have the scenario where using SAS tokens for authentication is not considered secure enough.
In our scenario we use managed identities to relate the application connecting to a namespace directly through a managed identity. We would also like to apply this principle for tooling like ServiceBusExplorer.

see https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/Program.cs

**Comment by SeanFeldman** [comment] 2020-01-08 16:30
Duplicate of https://github.com/paolosalvatori/ServiceBusExplorer/issues/392

**Closed by SeanFeldman** 2020-01-08 16:30 UTC
Labels: duplicate
