### ISSUE TITLE
Update "Forward To" of queue failed

### ISSUE THREAD

**Issue by ToMakeSense** [paolosalvatori/ServiceBusExplorer#384] opened 2019-10-11 11:07 UTC
I am using the lastest version(ServiceBusExplorer-4.1.112.zip) , I can't  configurate "Forward To" of queue by clicking **Update** button.
![image](https://user-images.githubusercontent.com/6244148/66646973-3dd39900-ec5a-11e9-98c7-eea7f7beef0b.png)

see outputs below in the log window:
```log
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:aca8aa30-ace2-400c-9df9-3fbe037bda1a_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:07. Method <UpdateQueue>b__0: retry 1 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:e8fdb830-4483-4050-b717-59409b92766a_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:07. Method <UpdateQueue>b__0: retry 2 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:363cccac-0d99-40a3-b403-188c3ddbc947_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:08. Method <UpdateQueue>b__0: retry 3 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:83191c6b-5fdb-4dd0-8e2d-0c7e0a31bf6c_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:09. Method <UpdateQueue>b__0: retry 4 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:1416601c-999f-4233-9b08-f40feff19efe_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:10. Method <UpdateQueue>b__0: retry 5 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:e70fd581-4e45-477f-a101-75f299534b92_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:10. Method <UpdateQueue>b__0: retry 6 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:ab926d70-4bcf-4ef8-ba57-2b2427dfc5ba_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:11. Method <UpdateQueue>b__0: retry 7 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:e9b81184-3cfb-48e4-9375-a7201e4e9145_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:12. Method <UpdateQueue>b__0: retry 8 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:06b77111-e849-4436-bb85-8b096ffcc9fa_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:13. Method <UpdateQueue>b__0: retry 9 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:33e46a96-cc6d-48a4-bb6a-1293049fa79c_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:13. Method <UpdateQueue>b__0: retry 10 of 10.
<18:51:16> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:0bdb256e-6a6f-49c9-9e3d-acbda3b70610_G10, SystemTracker:[myservicebusnamespacename].servicebus.windows.net:queue.[myqueuename], Timestamp:2019-10-11T10:51:14
<18:51:16> InnerException: The remote server returned an error: (400) Bad Request.
```

**Comment by ToMakeSense** [comment] 2019-10-11 11:10
I was trying to use this work around suggested in this issue #301

**Comment by SeanFeldman** [comment] 2019-10-11 13:42
I'm not aware of any known issues with auto-forwarding. Please provide
exact steps to reproduce this behaviour. Including names of the queues and
their configuration.

**Comment by ToMakeSense** [comment] 2019-10-11 16:36
@SeanFeldman  Thanks for your quick reply.  see below.

I created two Queues named: **MainQ** and **TempQ**  with the same configuration below:
![image](https://user-images.githubusercontent.com/6244148/66667559-de8b7e00-ec85-11e9-999c-cdeeefa8f27e.png)

Then I seleted **MainQ** and update the `Foward Dead Letered Messages To`  with **TempQ**, all these steps finished successfully.
![image](https://user-images.githubusercontent.com/6244148/66668204-4098b300-ec87-11e9-8b9b-5ba6dfbc658b.png)

``` log
<16:15:17> The queue MainQ has been successfully created.
<16:15:55> The queue TempQ has been successfully created.
<16:16:15> The queue MainQ has been successfully updated.
``` 
Then I seleted **TempQ** and update the `Foward To` with **MainQ**, it failed.
![image](https://user-images.githubusercontent.com/6244148/66668674-5195f400-ec88-11e9-9411-a5437550ef10.png)

```log
<16:16:47> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:775bcd44-d688-42f8-a0e7-1f9d1fd51eae_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:40. Method <UpdateQueue>b__0: retry 1 of 10.
<16:16:47> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:d8114a1c-8046-4f90-8ce1-14fdbe296753_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:40. Method <UpdateQueue>b__0: retry 2 of 10.
<16:16:47> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:af8fe9ea-9216-4ff8-a27b-3c68a41da0cf_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:41. Method <UpdateQueue>b__0: retry 3 of 10.
<16:16:47> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:7632b865-577a-45b3-96fc-2fbe8f6a407e_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:42. Method <UpdateQueue>b__0: retry 4 of 10.
<16:16:47> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:717ce1f0-2e31-483c-9f8c-465264e7c706_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:43. Method <UpdateQueue>b__0: retry 5 of 10.
<16:16:48> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:6e45b449-75ea-4193-9ff2-64c714d5ee95_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:43. Method <UpdateQueue>b__0: retry 6 of 10.
<16:16:48> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:badbc247-0ce7-44c3-a434-e91dd4599b57_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:44. Method <UpdateQueue>b__0: retry 7 of 10.
<16:16:48> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:abdf8871-c6ff-45b4-a092-0547298c758d_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:45. Method <UpdateQueue>b__0: retry 8 of 10.
<16:16:48> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:657aa669-53e2-438f-a81b-a9eac11c4850_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:46. Method <UpdateQueue>b__0: retry 9 of 10.
<16:16:48> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:0d67fa73-b72e-48ab-91a2-ef76e8740e38_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:46. Method <UpdateQueue>b__0: retry 10 of 10.
<16:16:48> Exception: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:6e8526da-5ab7-4fb1-8c23-c955f8e36461_G4, SystemTracker:service-bus-01.servicebus.windows.net:TempQ, Timestamp:2019-10-11T16:16:47
<16:16:48> InnerException: The remote server returned an error: (400) Bad Request.
```

**Comment by SeanFeldman** [comment] 2019-10-11 17:04
You're setting default time to live on TempQ on a forwarding queue. That's a conflicting request, so the broker is throwing a not so nice error. Remove Default Message TTL value and it should work.

**Comment by SeanFeldman** [comment] 2019-10-11 17:22
Long story short - this is by design. Unfortunately, w/o a clear exception message the internal implementation of the broker is bleeding out. For every forwarding queue, the broker sets up a receiver to pump the messages. When a queue is a session-enabled queue, the receiver must be set up appropriately. If it's not, then the exception is thrown. With your forwarding queue, disable Sessions and it will work. I also raise an issue for the broker team to fix that exception. https://github.com/Azure/azure-service-bus/issues/317

**Comment by paolosalvatori** [comment] 2019-10-17 08:42
Thanks @SeanFeldman, @ToMakeSense please let us know if we can proceed and close this issue, which indeed is not a tool issue. :)

**Comment by ToMakeSense** [comment] 2019-10-17 10:46
@SeanFeldman @paolosalvatori I thought only when both of the queues get session-enabled, the `Foward To` and `Foward Dead Letered Messages To`  functionality are able to worked well. after testing, it's not the case. so it's OK for me.

---

But I got even more confused regarding the two `Foward` topics after more testing. I am a freshman in Queue related topic 😢.

If  I got both `Foward To` and `Foward Dead Letered Messages To` enabled for MainQ and TempQ, I found the messages would end up in DLQ,  sometimes the messages was in MainQ, sometimes it‘s in TempQ. 

If I manualy got one of `Foward To` and `Foward Dead Letered Messages To` enabled to see what happend. the messages sometimes would lost, and I couldn't find it any more.

Besides, I found the `Message System Properties` can't be displayed for DLQ messages.
![image](https://user-images.githubusercontent.com/6244148/67001397-343faa80-f10c-11e9-8d2b-c5d1254e8e48.png)

**Comment by paolosalvatori** [comment] 2019-10-17 13:29
Hi @ToMakeSense, apart from the problem of the visualization of system properties for DLQ message,  it looks to me that this is more an issue of Service Bus Messaging rather than a problem of the tool. In this case, why don't you try to explain your scenario in an issue at https://github.com/Azure/azure-service-bus/issues?

**Closed** 2020-11-20 12:13 UTC
Labels: wontfix
