### ISSUE TITLE
SBE is confused about the count of Active and Deadletter messages in 2 queues that I use

### ISSUE THREAD

**Issue by eugen-nw** [paolosalvatori/ServiceBusExplorer#415] opened 2020-01-21 16:55 UTC
The numbers next to the queue names show one thing, yet when I retrieve the two types of messages I get a different picture.

Could this behavior be caused by a bug in the tool or is that Service Bus namespace in some confused state?

![SBE](https://user-images.githubusercontent.com/15199814/72825198-760c4f80-3c2b-11ea-9f7d-32b63add0f6f.png)

![PS](https://user-images.githubusercontent.com/15199814/72825232-83293e80-3c2b-11ea-9d1b-30f135fcdc48.png)

**Comment by SeanFeldman** [comment] 2020-01-21 22:54
What version of the tool are you using?

**Comment by eugen-nw** [comment] 2020-01-22 16:14
Thanks very much for looking into this!  I'm running the latest version.

![image](https://user-images.githubusercontent.com/15199814/72911552-1e371c80-3cef-11ea-8556-d5dd42769a7b.png)

**Comment by SeanFeldman** [comment] 2020-01-22 19:11
That's peculiar given [4.1.112](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/4.1.112) is the last version we've released 🙂
I suspect that's an old version of the tool that didn't report version correctly.
Could you please try the [latest](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/4.1.112) and see if that's still the case? Also, when you do that, please give it a go on a different namespace as well. Thank you.

**Comment by kylefender** [comment] 2020-01-22 19:38
Hi, I just came across this tool and ran into this exact problem. I used chocolately to install and that currently has 4.1.113 listed as the latest version. So is that the wrong install?

https://chocolatey.org/packages/ServiceBusExplorer

**Comment by SeanFeldman** [comment] 2020-01-22 19:48
@paolosalvatori @ErikMogensen any idea where that version is coming from? GitHub does not have a tag for 4.1.113 ([tags are auto-generated](https://github.com/paolosalvatori/ServiceBusExplorer/tags) when we release) and last released version was [4.1.112](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/4.1.112).

Looking at the Chocolatey history, there's something goofed up.
![image](https://user-images.githubusercontent.com/1309622/72928594-81d44080-3d15-11ea-8a28-f1fb838acbaf.png)

We should unlist that version.

**Comment by kylefender** [comment] 2020-01-22 20:05
I don't understand how 113 was built before 112 but it looks like both releases were created from the same PR, but a day apart. Here's the AppVeyor information:

113 => https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/22992443
112 => https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/23001341

Here's the PR it was built from: https://github.com/paolosalvatori/ServiceBusExplorer/commit/f1a7d85ef09aed45149e34247a8f70b4f7c6b571

![image](https://user-images.githubusercontent.com/5283190/72929416-c7016e00-3d27-11ea-96d9-4e444b7c68f9.png)

**Comment by SeanFeldman** [comment] 2020-01-22 20:15
Release 4.1.112 was a planned release and here's the PR: #314
Release 4.1.113 is a mystery unless the branch was merged into master.
We'll be switching to Release Flow and that will take these woes away.

I have unlisted 4.1.113. Back to the issue - could you try the version from GitHub and see if you run into this exact issue? Thank you.

**Comment by kylefender** [comment] 2020-01-22 20:37
I pulled down the release from GH and I am no longer receiving the error. It could have also been user error in that I wasn't refreshing the treeview UI on the left before retrieving the messages.

I don't know if the OP is still having trouble.

Thanks for your help!

**Comment by eugen-nw** [comment] 2020-01-22 21:34
Thanks very much!  I downloaded and installed 4.1.112 and that also has issues with messages in the 'request2' queue:

![image](https://user-images.githubusercontent.com/15199814/72936123-75eb7d00-3d1b-11ea-8ad8-e7f8d993d2e7.png)

![image](https://user-images.githubusercontent.com/15199814/72936360-e1cde580-3d1b-11ea-83f7-596314d66298.png)

**Comment by eugen-nw** [comment] 2020-01-22 22:06
I'm following this issue with Microsoft as well and they suspect that SBE's Peek is returning some cached messages.  'Receive and Delete' on the request2 queue returned 0, but if I do a Peek right afterwards, I see those 15 messages again.

**Comment by SeanFeldman** [comment] 2020-01-22 22:27
>  they suspect that SBE's Peek is returning some cached messages.

@eugen-nw that could be a bug. I've tried the following and didn't get the issue you're running into.
1. Have 3 messages in a queue `test`
1. Select the queue
1. Click <kbd>Messages</kbd>
1. Select `Receive and Delete` and click <kbd>ok</kbd>
1. Click <kbd>Messages</kbd>
1. Select `Peek` and click <kbd>ok</kbd>

My output looks OK
![image](https://user-images.githubusercontent.com/1309622/72940176-91f71a80-3d2b-11ea-943f-aab748869337.png)

Can you provide complete steps to repro? I'd like to be able to see that happening on my end as well. Thank you.

**Comment by eugen-nw** [comment] 2020-01-22 22:30
This is the first time I'm seeing this erratic behavior, you may want to connect to the message queue in question.  Could you please send me an email to edaroczy@boldiq.com?

**Comment by SeanFeldman** [comment] 2020-01-22 23:25
Got to repro this. Also noticed your queues are express queues.
![image](https://user-images.githubusercontent.com/1309622/72943645-d981a480-3d33-11ea-8ddb-444c6f016b68.png)

Could you try the same repro steps on a queue that is **not** express (`Enable Express` is not checked off).

**Comment by eugen-nw** [comment] 2020-01-22 23:48
Thank very much @SeanFeldman  I tried Peek-ing the Active and Deadletter Queue messages on the 'requests3' queue.  Both returned 0.  What else would you like me to try, use this queue for a while?

**Comment by SeanFeldman** [comment] 2020-01-23 00:12
Yeah, use this queue and see if you can repro the issue. If not, that means the problem is with the Express entity on the broker side and raising an issue with the ASB broker repository linking to this thread would close this issue.

**Comment by ErikMogensen** [comment] 2020-01-23 22:20
@eugen-nw , Please increase the values for Server timeout and Receive timeout and check if that makes a difference.

If that didn't help please turn on "Enable batched operations" and Update. Then turn off "Enable batched operations" and Update again. That will trigger a reset of the broker(s) which may fix the problem.

**Comment by eugen-nw** [comment] 2020-01-27 23:16
Thanks @ErikMogensen  I'm afraid that I cannot change those timeouts.  I did not see the option in either of:
- the Azure portal
- SBE
- resources.azure.com

**Comment by ErikMogensen** [comment] 2020-01-28 07:03
Those are SBE settings. They are located in the View | Options dialog.

Change the "Enable batched operations" setting from SBE too. It is a setting on the queue.

**Comment by eugen-nw** [comment] 2020-01-28 16:52
Thanks very much @ErikMogensen!  I set both values to 10 seconds.

**Comment by eugen-nw** [comment] 2020-01-28 16:59
Is "Enable batched operations" ON/OFF the only queue setting that resets the brokers please?

**Comment by ErikMogensen** [comment] 2020-01-28 17:12
I guess 10 seconds didn't help. Try 60 seconds for both values. 

There are other settings that will reset the brokers but they may cause a bigger change. Enable Batched Operations has worked for me.

If this is a Premium namespace that may not work. It sounds like this is a partitioned, standard namespace though.

**Comment by eugen-nw** [comment] 2020-01-29 16:28
Yes, it is a Standard & Partitioned queue.  SBE seems to work now, the displayed counts of messages next to the queue's name matches the counts returned by the two "Receive [Deadletter Queue] Messages" commands .  I am down to using only my original "requests" queue.

So in conclusion, this is what we've done to it in order to get it to work.  All within SBE.

1.  "Enable Express" went into unchecked state.  Which is good anyways because it is not desirable to lose any messages should crashes occur.
2.  We went through the uncheck -> Update -> check -> Update cycle of the "Enable Batched Operations" option.  This will reset the brokers.
3.  In View -> Options both Receive and Server Timeout values are set to 60.

**Comment by ErikMogensen** [comment] 2020-01-29 18:59
Good that you put the steps and the result here. I would expect that that turning off Express would reset the brokers, but perhaps it needed multiple resets or it was the timeout increases that made it work.

I just created an issue for increasing these timeouts, #420 .

**Comment by SeanFeldman** [comment] 2020-01-29 20:34
Rarely I've seen "Enable Express" needed.

**Comment by paolosalvatori** [comment] 2020-02-17 10:56
Sorry guys to get to the discussion quite late, but as @ErikMogensen can confirm, I was quite busy in the last few weeks. @eugen-nw, @SeanFeldman, @kylefender  an I proceed and close the issue?

**Closed** 2020-02-17 13:04 UTC
